apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: http-load-balancing
  namespace: demo
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - http-load-balancing
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: http-load-balancing/aws
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: http-load-balancing
  name: http-load-balancing-subscription-aws
  namespace: demo
spec:
  channel: ggithubcom-ggoksu-hybrid-cloud-demo-ns/ggithubcom-ggoksu-hybrid-cloud-demo
  placement:
    placementRef:
      kind: Placement
      name: service-interconnect-placement-aws
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: http-load-balancing/azure
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: http-load-balancing
  name: http-load-balancing-subscription-azure
  namespace: demo
spec:
  channel: ggithubcom-ggoksu-hybrid-cloud-demo-ns/ggithubcom-ggoksu-hybrid-cloud-demo
  placement:
    placementRef:
      kind: Placement
      name: service-interconnect-placement-azure
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: http-load-balancing/hpe
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: http-load-balancing
  name: http-load-balancing-subscription-hpe
  namespace: demo
spec:
  channel: ggithubcom-ggoksu-hybrid-cloud-demo-ns/ggithubcom-ggoksu-hybrid-cloud-demo
  placement:
    placementRef:
      kind: Placement
      name: service-interconnect-placement-hpe

