apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: online-boutique
  namespace: demo
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - online-boutique
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: online-boutique-subscription-aws
  namespace: demo
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: onlineboutique/aws
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: online-boutique
spec:
  channel: ggithubcom-ggoksu-hybrid-cloud-demo-ns/ggithubcom-ggoksu-hybrid-cloud-demo
  placement:
    placementRef:
      name: service-interconnect-placement-aws
      kind: Placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: online-boutique-subscription-azure
  namespace: demo
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: onlineboutique/azure
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: online-boutique
spec:
  channel: ggithubcom-ggoksu-hybrid-cloud-demo-ns/ggithubcom-ggoksu-hybrid-cloud-demo
  placement:
    placementRef:
      name: service-interconnect-placement-azure
      kind: Placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: online-boutique-subscription-hpe
  namespace: demo
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: onlineboutique/hpe
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: online-boutique
spec:
  channel: ggithubcom-ggoksu-hybrid-cloud-demo-ns/ggithubcom-ggoksu-hybrid-cloud-demo
  placement:
    placementRef:
      name: service-interconnect-placement-hpe
      kind: Placement

