apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    skupper.io/address: "payment-processor"
    skupper.io/port: "8080"
    skupper.io/proxy: "http2"
  labels:
    app: payment-processor
  name: payment-processor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-processor
  template:
    metadata:
      labels:
        app: payment-processor
    spec:
      containers:
        - name: payment-processor
          image: quay.io/skupper/patient-portal-payment-processor
          ports:
            - containerPort: 8080
